### ISSUE TITLE
Failing to use datagem

### ISSUE THREAD

**Issue by LudoAcciai** [giacbrd/python-dandelion-eu#4]
I am just trying to follow this example:

from dandelion import Datagem 

YOUR_APP_ID='2d30226a'
YOUR_APP_KEY='98e8e00736738db994a3e8d515a6402a'

d = Datagem('administrative-regions', app_id=YOUR_APP_ID, app_key=YOUR_APP_KEY)
for obj in d.items.select('acheneID')[:10]:
    print(obj)

but i get this error:

Traceback (most recent call last):
  File "/Users/Ludovica1/Desktop/dande.py", line 9, in <module>
    for obj in d.items.select('acheneID')[:10]:
  File "/Library/Python/2.7/site-packages/dandelion/datagem.py", line 96, in **iter**
    response = self.datagem.do_request(params, method='get')
  File "/Library/Python/2.7/site-packages/dandelion/base.py", line 88, in do_request
    raise DandelionException(obj)
dandelion.base.DandelionException: usage limits are exceeded

**Comment by enricomarchesin** [comment]
Hi Ludovica. 

First of all an important advice: while asking help online, always hide the credentials you are actually using. They must be treated with the same attention you give to your passwords, since anyone who gets access to them, can use the services you subscribed to in your place.

For security reason we had to reset your appKey: you can find the new one in your dashboard at https://dandelion.eu/profile/dashboard/

Can you please try again with the new credentials?
